### ISSUE TITLE
Network Status Graphs don't render [HELP]

### ISSUE THREAD

**Issue by derwincabral** [tobychui/zoraxy#200] opened 2024-06-13 20:42 UTC
**What happened?**
More of a visual issue, Network Status doesn't populate the graph. Says "Graph Renderer Paused"
Did an inspect element:  
```
<div id="networkActivityPlaceHolder" style="display: none;">
    <p style="opacity: 0.5;"> Graph Render Paused</p>
</div>
```

**Describe what have you tried**
Not much, This is running in docker with the default compose file as shown below. Went to Network Tools> interface and eth0 is there with 172.19.0.2/16

**Describe the networking setup you are using**
Here are some examples, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy? yes 
- Your Zoraxy version? 3.0.6
- Are you using Cloudflare? yes

**Additional context**
All used features work as intended. Tests so far have been pretty great. 

compose.yaml
```
version: "3.3" #can be removed if you are using latest version of docker
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    ports:
      - 80:80
      - 443:443
      - 8000:8000/tcp
    volumes:
      - ./config:/opt/zoraxy/config/
    environment:
      ARGS: -noauth=false
    restart: unless-stopped
networks: {}
```
![image](https://github.com/tobychui/zoraxy/assets/100728215/d49fe801-09bc-4421-82b7-82ea63a5bbf3)

**Comment by tobychui** [comment] 2024-06-14 02:04
The "Graph Renderer Paused" is in `display: none;` state, which is irreverent to the problem (this text only show up when you are focusing on other tabs to save some resources). So I guess this is just your front-end bugged for some reason. Try test with another browser, stop your adblocks or check for console error message and something like that. 
If it is a backend problem, you should be able to see all stats being 0 instead of an empty graph as shown.

**Comment by barto95100** [comment] 2024-06-14 13:15
Sale problem


on 3 differents browser , ipad and on mac 

it's necessary to refresh the browser most time to graph show

**Comment by derwincabral** [comment] 2024-06-14 19:45
This is the only thing that's erroring out under the console. Tried from the same workstation in firefox with the same result (using edge no extensions atm on bare server 2019) . Not sure if "ao_module.js" is relevant or not. Will try expose this late to another system to see if I have the same result. Is there a recommended browser?

![image](https://github.com/tobychui/zoraxy/assets/100728215/e81fbddf-afad-493c-b768-c82390daa70b)

**Comment by tobychui** [comment] 2024-06-15 03:55
@derwincabral The aomodule is for ArozOS integration test (seems I forgotten to remove it when packing the release). But graph rendering should not be effected by missing that script.

I personally use Firefox for debugging (as it run on FF, it probably run on most other browsers). The graph do sometimes shows  weird issue on my side (with adblock enabled, take a few fresh to fix it), and I am too busy to optimise it so I keep it as it is for now 😅

**Comment by JokerQyou** [comment] 2024-08-01 15:41
Same issue here, but I have no console errors or warnings in browser devtools. Reproduced with Vivaldi browser (based on Chromium). Safari works. So it's only Chrome and Chromium-based browsers that are affected.

**Comment by JokerQyou** [comment] 2024-08-01 15:48
Also this part:

> The "Graph Renderer Paused" is in display: none; state, which is irreverent to the problem (this text only show up when you are focusing on other tabs to save some resources). 

is not optimal.

When another browser tab is focused, the network graph shows "Graph Renderer Paused", but it continues to poll the network stats. If there's no consumer then there's no need to poll these data. Maybe it's more efficient to just pause the polling timer when tab is not focused.

**Comment by JokerQyou** [comment] 2024-08-01 15:59
I suspect it's because of these two lines that are commented out:

https://github.com/tobychui/zoraxy/blame/1d965da7d080eb26b14548f12bc6240ce91a24f1/src/web/components/status.html#L701-L702

However currently I don't have a test environment to debug. Looks like the `rxValues` and `txValues` are initialized to empty array, and get updated to polled data every 1 second. But these are just plain Javascript arrays instead of some reactive type or observables, so in `updateChart()` nothing happens, the chart stays empty.

**Comment by tobychui** [comment] 2024-08-02 00:11
@JokerQyou I don't think that two lines are related to the issue here. You see, I cannot reproduce the same issue with Chrome (ver 127.0.6533.89) even these two lines are commented out.

![圖片](https://github.com/user-attachments/assets/c2e1f2bd-0554-40c9-b029-d6c60e660720)

The reason why it was commented was because it caused lag in previous versions.

**Comment by JokerQyou** [comment] 2024-08-02 02:34
Then I guess we need to figure out a new way to update the chart.

@derwincabral @barto95100 Could you kindly test if overriding the `updateChart` function in the browser's devtools console fix this issue?

**Comment by barto95100** [comment] 2024-08-02 08:50
when i test to add code in console:

![CleanShot 2024-08-02 at 10 45 45@2x](https://github.com/user-attachments/assets/36122986-b2ec-4688-971b-fa871b308129)


no problem for me on vivaldi in macos it's work directly, but with Arc browser based on chromium (Version 1.54.0 (52220)
Chromium Engine Version 127.0.6533.89) the graph don't show :( 

to work with chromium is necessary to refresh multiple time and after that, this is i have on console :
![CleanShot 2024-08-02 at 10 48 36@2x](https://github.com/user-attachments/assets/9b4da6aa-1a40-4ade-9d17-242e73fcddb6)


on firefox no problem 

the problem seems to come from chromium

**Comment by JokerQyou** [comment] 2024-08-02 09:24
You entered French text, I don't think it's valid Javascript code. You can copy the function here:

```js
function updateChart() {
    networkStatisticChart.data.datasets[0].data = rxValues;
    networkStatisticChart.data.datasets[1].data = txValues;
    if (networkStatisticChart != undefined){
        networkStatisticChart.update();
    }
}
```

and paste it into devtools console.

**Comment by JokerQyou** [comment] 2024-08-02 14:01
It has something todo with the timing of the network requests initialized by `initChart` and `fetchData`. Specifically this part:

https://github.com/tobychui/zoraxy/blob/1d965da7d080eb26b14548f12bc6240ce91a24f1/src/web/components/status.html#L585-L597

If the network request in `fetchData` is lagged, by the time it receives the first batch of traffic stats, `rxValues` and `txValues` has both been taken ownership by Chart.js. But in the response processing block they are being replaced with new Javascript arrays, so Chart.js lost the ability to track their changes. It can be fixed by using spread syntax or for loop to push the first batch of values into these arrays instead of re-assigning variables.

**Closed** 2024-08-07 05:49 UTC
Labels: help wanted
