### ISSUE TITLE
[BUG] Unable to generate any certificates with Lets Encrypt

### ISSUE THREAD

**Issue by Sillver101** [tobychui/zoraxy#309] opened 2024-09-16 18:34 UTC
I am having an issue when I try and generate Certificates for any of my subdomains. I followed all steps and confirmed my services are active. I can reach them through Zoraxy from the outside world (I get a cert Error due to the delf signed cert at the moment).
However when i try and generate a certificate with the ACME tool i get the following error.

"Error: one or more domains had a problem: [sub.domain.tld] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: query timed out looking up A for sub.domain.tld; DNS problem: query timed out looking up AAAA for sub.domain.tld"

At my Domain registrant the DNS records are using CNAMEs not A Records, However this shouldn't be an issue as i am able to generate certificates using CNAME Records with other acme tools.

I basically have the following records for clarity
"sub.domain.tld IN CNAME some.other.domain."

To Reproduce
Use ACME tool within zoraxy and try to create a certificate from letsencrypt using.

Expected behavior
Certificates are generated and deployed inside zoraxy successfully and automatically.

**Screenshots**
![image](https://github.com/user-attachments/assets/be200483-a3cb-4f70-9f5e-65f409282734)

**Host Environment (please complete the following information):**
-  Arch: AMD64 (QEMU VM)
 - Device: Proxmox VM
 - OS: Ubuntu 
 - Version: 22.04.3 LTS (Jammy)
 - Docker Version:  27.2.1

Any help would be appreciated as i am at a loss right now

**Comment by PassiveLemon** [comment] 2024-09-16 19:05
Duplicate of https://github.com/tobychui/zoraxy/issues/307

**Comment by PassiveLemon** [comment] 2024-09-16 19:06
Oh wait sorry this looks different

**Comment by Sillver101** [comment] 2024-09-16 19:16
I am supposedly running the latest image 
![image](https://github.com/user-attachments/assets/0f049048-f34f-4284-b419-d5dae90a4b53)

**Comment by PassiveLemon** [comment] 2024-09-16 19:29
I'm skeptical of ACME errors at the moment because of a certificate issue in the Docker container but since there's nothing mentioned about that, it's probably unrelated. I don't exactly know how to troubleshoot ACME error messages but I do recall having a similar problem when running a local DNS server for my domain. Are you using a DNS server with your domain set up as a zone?

**Comment by Sillver101** [comment] 2024-09-16 19:34
I did the the other issue you mentioned and made sure the ca-certificate package was up to date. No local DNS servers running. I've had issues with the same in the past. I make sure any device now that will be serving internet facing services (weather behind a proxy or not) uses Public DNS servers for all of their DNS requests. and my internal network forwards all queries to public DNS servers as well.

**Comment by PassiveLemon** [comment] 2024-09-16 19:56
Oh haha that's good and unfortunate to hear. If you are comfortable with building Docker images, I do have a PR open to fix the CA issue (https://github.com/tobychui/zoraxy/pull/308) that you could apply locally.

Otherwise, you can attach to the container, run `apt install ca-certificates` and then attempt to get the certificate again to confirm that your issue is resolved

**Comment by Sillver101** [comment] 2024-09-16 20:01
So ignore my previous comment xD.

Regarding building docker. I have honestly only started working with them recently so yeah i am running full force into a slightly flexible wall with regards to this. Luckily years of working in the tech field has given me the troubleshooting tools i seem to need.

I managed to resolve the error regarding the "Failed to verify certificate"

To resolve the verification error i ran 
update-ca-certificates --fresh
on both he host and then inside the docker container. I then restarted the docker container and the logs now show it is using the certificate from the local store and verifying it.

I was able to restart the container multiple times and it seems to have persisted.

But as i mentioned i am now back to the same error i logged.

Section of Logs in pastbin for clarity sake which i hope helps explain what i am talking about
https://pastebin.com/R1NFKX1R

**Comment by PassiveLemon** [comment] 2024-09-16 20:05
Unfortunately I don't really know how to troubleshoot this so I'll leave that for @tobychui

**Comment by Sillver101** [comment] 2024-09-16 20:07
Thanks for the Assistance. If there is anything else needed for troubleshooting let me know. Obviously ill wait for Tobychui to respond when he has a chance, I know how it can get busy

**Comment by tobychui** [comment] 2024-09-17 02:57
@Sillver101 This error seems to cause by the CA cannot reach your Zoraxy instance due to a DNS error. This can be caused by many reasons including
- You haven't setup your DNS record on your domain correctly (does the subdomain you are requesting certificate exists on your domain's DNS record?)
- DNS record is still propagating (Wait 24 hours and try again)
- Your subdomain is not reaching Zoraxy (Seeing you are using Promox here, have you setup your virtual networking adapter correctly? Can you reach Zoraxy using your subdomain and see the Zoraxy build-in self-signed certificate?)

This is mostly cause by specific networking issue and usually in cases like these, there aren't much we can help. Thought, with the current docker image bug, I think there might also be chances that it is related to the DNS config in the docker's Ubuntu. If you have checked all the above possible reasons and still cant get it working, try update your docker image to the latest version (v3.1.1r3) when it is ready.

**Comment by Sillver101** [comment] 2024-09-17 05:22
Hi @tobychui 

Thanks for the feedback. I'll see in order just so I don't lose track of it. (Also apologies if the formatting has gone weird. I'm replying from my phone)

I figured it would be something with acme not reaching the instance but for the life of me couldn't figure out why. The main concern was that it was specifically looking for A or AAA DNS records instead of cnames which is what I have setup. I assume then this is not a setting in the docker image somewhere?

- the DNS records on the domain is setup using a cname record
- the DNS propagation is completed and I. Able to reach the instance from external devices/connections
-the subdomain is also reaching zoraxy correctly as I am able to get to it through zoraxy and when enabling SSL/TLS it gives me the self signed cert and I am able to inspect it

So regarding the above I have setup one service I am proxying with an SSL certificate using zerossl (I ended up creating an account to get the keys needed I was hoping to avoid having to do this with acme but it's not. The worst scenario) and it was setup without issues so it looks like it is 100% only with the acme side of it.

I will wait for the updated docker container and see if that resolves the issue. Thanks for all the assistance and the time to look at the bug.

**Comment by SuitDeer** [comment] 2024-10-22 18:27
I had the same error.

The solution for me was to enable the HTTP Server:

![grafik](https://github.com/user-attachments/assets/45260cef-ed43-44ff-9198-8df3a5f59790)

Because ACME Requests are issued over Port 80

**Comment by tobychui** [comment] 2024-11-04 13:43
Automatic HTTP server toggle has been added in v3.1.2. In this new version, if you haven't enable port 80 listener, Zoraxy will automatically start it up for you and turn it off after certificate request is done.

**Closed by tobychui** 2024-11-04 13:43 UTC
Labels: bug

**Comment by ChronoWerX82** [comment] 2025-05-09 13:01
> Automatic HTTP server toggle has been added in v3.1.2. In this new version, if you haven't enable port 80 listener, Zoraxy will automatically start it up for you and turn it off after certificate request is done.

Running here version 3.2.1 and I have to deactivate TLS manually, to generate or renew certificates. ACME Auro-Renewer can't work automatic

**Comment by Sillver101** [comment] 2025-05-09 13:12
Not sure if this will help anyone (And i honestly forgot about this) My primary issue was resolved by changing to a static IP.

The initial setup i had was my Proxy hostname at my DNS Provider was using a CNAME Record pointing to a DYNDNS hostname.
i.e app.mydomain.com <-> proxy.mydomain.com <-> dyndnshostname

I updated to using a static IP and changed the Proxy host from a CNAME to an A Records and acme SSL Certificates work wiht no issues. the auto renewal also works.
i.e app.mydomain.com <-> proxy.mydomain.com <-> static-IP

This seems to possibly be some sort of quirk with acme when you have are pointing a cname to a cname to a cname.

I know it might be confusing but that's what i experienced
