### ISSUE TITLE
[BUG] Container Continually Crashing

### ISSUE THREAD

**Issue by rdavey228** [tobychui/zoraxy#437] opened 2024-12-22 19:37 UTC
Container continually crashing

Unable to force replicate the issue, it happens at random intervals, maybe once, twice a day.

Only reason I know it's happening is because my uptime monitor tells me my sites have gone down. When I look at the docker host the container is down. 

To fix I just start the container again and it continues to run till it decided to crash again.

Running on a Raspberry pi under ubuntu 20.04.6 docker v24.07

I have attached everything that happens in my logs right as it happens. Don't know if thats helpful but I can't find anything in the logs that tells me what the issue is.

[Logs.docx](https://github.com/user-attachments/files/18223036/Logs.docx)

**Comment by tobychui** [comment] 2024-12-22 22:46
Closing as duplicate of #401

**Closed by tobychui** 2024-12-22 22:46 UTC
Labels: bug
