### ISSUE TITLE
[BUG] Docker container stops immediately after starting after latest update 

### ISSUE THREAD

**Issue by AzAel76** [tobychui/zoraxy#245] opened 2024-07-16 03:03 UTC
Pulled the most recent 3.0.8 update and container stops immediately after start. 

Only output in the Docker log is ...
Flag provided but not defined: -log 
Then "Zoraxy usage" followed by all the available switches. Then stops.

Platform: unraid 6.12
Custom template.

**Comment by tobychui** [comment] 2024-07-16 03:41
Hey @AzAel76,

Yes, this is a known problem and the fixes is in PR stage right now.
https://github.com/tobychui/zoraxy/pull/246

**Comment by Morethanevil** [comment] 2024-07-16 03:42
Take a look [here](https://github.com/tobychui/zoraxy/issues/241) ☝🏻

**Comment by mbah-dukun** [comment] 2024-07-16 06:04
Please Update your Docker Image to latest Docker Image

**Comment by AzAel76** [comment] 2024-07-16 06:10
My apologies I forgot to remove the default 'is:open' flag from my search or I would have noticed.

**Comment by ExXxtr3me** [comment] 2024-07-16 06:30
3.0.9 starts fine but all my proxies are gone. I can see them in the new proxy folder and the log state there are loaded but they are missing in Zoraxy. Creating a new Proxy in the Gui creates a config in the folder but i can't delete the new Proxy in the gui.

**Comment by tobychui** [comment] 2024-07-16 06:45
@ExXxtr3me Oh...

As the upgrade module checks where your previous version is and try to upgrade to the next version if something is not compatible, I didn't design it to support skip version upgrade like v3.0.7 -> v3.0.9. You need to first run 3.0.8 once, let the auto upgrader kicks in to convert the format to v3.0.8, then start the v3.0.9. 

Alternatively, you can manually map them to the new json format for upstreams. But that would take some time as well. I will see if I can fix the upgrade system in next release to support cross versions config upgrade.

**Comment by ExXxtr3me** [comment] 2024-07-16 06:50
I understand, but the problem is that 3.0.8 isn't starting for me.

**Comment by AzAel76** [comment] 2024-07-16 06:53
Same issue here.
Output after restarting hoping the 3.0.8 -> 3.0.9 conversion would occur (it didn't)

[system:info] xxx.xxx.xxx ->  routing rule loaded
2024/07/16 06:50:16 Unable to setup upstream : invalid endpoint config

**Comment by tobychui** [comment] 2024-07-16 07:00
Ok here is a quick fix. If you go into the `conf/proxy/` folder, if the upgrade failed, you will see the line `OriginIpOrDomain` become an empty string.

![圖片](https://github.com/user-attachments/assets/610c2c7c-180a-4939-b96a-1b9a47d8ec7e)

For a quick fix, you can manually fill in this line from your config backup. Alternatively, you can roll back to v3.0.7 and wait for the next release which (hopefully) will fix the skip version upgrade issue or use v3.0.8 by rebuilding your docker image.

**Comment by AzAel76** [comment] 2024-07-16 07:10
For me I'm just recreating them, test purposes since configuring Docker Socket 

I did notice when selecting from dockers it's overwriting the **Matching keyword / Domain** field with the container name.

**Comment by tobychui** [comment] 2024-07-16 07:21
@AzAel76 I am not sure how this bug will behave in docker environment as the default CI/CD test cases only runs in non-dockerize environment. But I guess the fixes should be identical (by manually changing the upstream target IP / domain)

**Comment by tobychui** [comment] 2024-07-16 10:30
(Not a docker expert but) I have written up a basic upgrade guide for docker users. I have tested it in my VirtualBox VM with Portainer so I guess it should works.

https://github.com/tobychui/zoraxy/wiki/Updating-Zoraxy#updating-zoraxy-docker

**Comment by tobychui** [comment] 2024-07-31 14:55
This issue should be fixed with the new updater design. If there are any further issue, please create a new issue and I will follow up from there.

**Closed by tobychui** 2024-07-31 14:55 UTC
Labels: bug, docker
