### ISSUE TITLE
[HELP] doesn't work properly without JavaScript enabled

### ISSUE THREAD

**Issue by korderos** [tobychui/zoraxy#237] opened 2024-07-11 06:29 UTC
Hi !

I done all setup to have a configuration like : 
name.freeboxos.fr/admin -> 192.168.1.4:8081
name.freeboxos.fr/ebooks -> 192.168.1.4:8082

Route looks correct because I'm able to reach each page from ouside my local network
But.... each application return an error message : "We're sorry but xxxxxxx doesn't work properly without JavaScript enabled."
Applications work correctly when using local adress

Any idea about what missing ?

Thanks !

![image](https://github.com/tobychui/zoraxy/assets/19736640/944f0c3b-98cd-495a-bfbc-563a0233e8f2)

**Comment by tobychui** [comment] 2024-07-11 14:24
Hi @korderos,

Seems you are new to self-hosting with reverse proxy. If your application is using absolute path when including JavaScript (something like `/js/my_script.js` instead of `./js/myscript.js`), this errors shows up. This is expected behavior for virtual directories as it will rewrite the request before it reaches your origin server. 

Virtual directories are commonly used for resources folders that store images or javascripts and allow single host to share the resources over multiple sites. I guess you are trying to reverse proxy a full website (with html and js) which is not the intended usage of virtual directories. 

There are two potential fixes for your use case.
1. Use a dedicated subdomain for the :8081 and :8082 server instead of virtual directories
2. Update the code in your origin server application which uses the base url of `????eeboxos.fr/admin` and `????eeboxos.fr/ebooks`.

If you got no further questions, you can close this issue after reading this.

**Comment by korderos** [comment] 2024-07-11 14:30
You're right my new :)
So, I won't be able to use reverse proxy because I can't get additionnal subdomain
I can't update code because there are applications from an appstore (casaos)
Thanks for your reply !

**Closed** 2024-07-11 15:29 UTC
Labels: help wanted
