### ISSUE TITLE
[BUG] old virtual directory doesn't get remove on uptime page

### ISSUE THREAD

**Issue by chatainsim** [tobychui/zoraxy#254] opened 2024-07-18 13:11 UTC
**Describe the bug**
When Virtual Directory are remove from a HTTP Proxy configuration, it still show up on Uptime page.

**To Reproduce**
1. Create a Proxy rules with Virtual Directory
2. Check on Uptime page that the virtual directory is monitored
3. Remove the Virtual directory from the HTTP Proxy configuration
4. Uptime for the removed virtual directory still present in the Uptime page.

**Expected behavior**
Virtual directory get removed from uptime page

**Host Environment (please complete the following information):**
-  Arch: amd64
 - Device: LXC container on Proxmox host
 - OS: Debian 12 Bookworm
 - Zoraxy Version: v3.0.9

![image](https://github.com/user-attachments/assets/ccd19355-440c-4711-941e-6aacd5753c59)
 
![image](https://github.com/user-attachments/assets/407f8f2f-dcb1-43c4-bb2d-b00289c70f7b)

![image](https://github.com/user-attachments/assets/54a617d1-5ddc-44e8-b7bf-029c0a6c3b46)

![image](https://github.com/user-attachments/assets/0f316acd-72e1-45bf-94ad-811d658d2980)

If the Proxy rules get deleted, than both are remove from Uptime page.

Thanks

**Comment by tobychui** [comment] 2024-07-19 03:38
Seems it was caused by some legacy code in updating the up-time monitor entries. A quick fix has been pushed to the v3.1.0 branch 👍🏻

**Closed** 2024-07-31 14:39 UTC
Labels: bug
