### ISSUE TITLE
SMTP server without credentials

### ISSUE THREAD

**Issue by tadikwa** [tobychui/zoraxy#162] opened 2024-05-20 21:54 UTC
Hello team,

It doesn't seem possible to add a local SMTP relay server without an identifier.
![2024-05-20_23h50_37](https://github.com/tobychui/zoraxy/assets/6054289/d067d4cf-7c03-4680-9edd-209594765f42)

**Comment by tobychui** [comment] 2024-05-21 02:07
For the sender email, it is just a part of the email content where you can fill in anything you want (e.g. noreply@yourdomain.com) . For no auth SMTP, this seems to be a duplicate of #80.

**Comment by tobychui** [comment] 2024-06-10 09:03
Password requirement is removed in v3.0.6. Now you should be able to save SMTP credentials without a password.

**Closed by tobychui** 2024-06-10 09:03 UTC
Labels: bug

**Comment by DaGrooves** [comment] 2024-06-10 12:19
It's not working for me. I'm using port 8025 to a mailrise server. 
But is get the error "Unencrypted connection" 
<img width="192" alt="Control Panel _ Zoraxy" src="https://github.com/tobychui/zoraxy/assets/41742621/33350221-1c38-4981-bb96-a77892e7e6a5">

**Comment by tobychui** [comment] 2024-06-10 12:27
@DaGrooves Golang SMTP library refuse to send email with non-TLS connection. Enable TLS on your mailrise server with `tls.mode` flag and try again?

**Comment by DaGrooves** [comment] 2024-06-10 12:54
@tobychui  Thanks for the quick reply :)
Is it possible to use zoraxy to get create a proxy rule that creates a Letsencrypt cert for the mailrise server at port 587?

**Comment by tobychui** [comment] 2024-06-10 13:00
@DaGrooves Uhh, isn't SMTP and HTTP are two different protocols? I don't think that is how SMTP over TLS works.

**Comment by DaGrooves** [comment] 2024-06-10 13:33
My thoughts exactly. Will find another solution.
Thanks for your effort.
