### ISSUE TITLE
Reverse proxy appears 404[HELP]

### ISSUE THREAD

**Issue by allmors** [tobychui/zoraxy#189] opened 2024-06-07 17:18 UTC
**What happened?**
Reverse proxy appears 404.]

**Describe what have you tried**
If the reverse proxy address is not a public IP, it will be 404
![image](https://github.com/tobychui/zoraxy/assets/93471589/5b1879e6-8e62-416e-92bb-4989dfe892bb)
![image](https://github.com/tobychui/zoraxy/assets/93471589/b4db265c-7c46-45f2-89c3-b7bd3a765bd2)

But my local service can be accessed normally
![image](https://github.com/tobychui/zoraxy/assets/93471589/221c4c8c-03dc-485e-b554-7236c7ea7bbf)

The most intuitive one is zoraxy, which runs on 8005. If my reverse proxy points to 127.0.0.1:8005, then it will also appear 404. If I use the public IP + port, then it will be normal.
![image](https://github.com/tobychui/zoraxy/assets/93471589/8b852ef3-2657-4523-8b71-eee346c6b42a)
![image](https://github.com/tobychui/zoraxy/assets/93471589/0a820125-0286-4a36-ae68-6d0059c1cd0e)

**Describe the networking setup you are using**
Here are some example, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy? [yes]
- Your Zoraxy version? [e.g. 3.0.4]
- Are you using Cloudflare? [no]
- Are your system hosted under a NAT router? [no](gpc cloud)
- DNS record (if any)

**Additional context**

**Comment by Morethanevil** [comment] 2024-06-07 22:35
Your request comes from the internet to your hostmachine and then in the docker container. 127.0.0.1, localhost points INSIDE the container., because Zoraxy runs inside the container. This is not a bug, this is normal. Your setup would work if it were not a container then localhost, 127.0.0.1 would be your host machine. 

This is why it works with your public IP and port ☺️

**Comment by tobychui** [comment] 2024-06-08 02:28
@allmors  This is expected behavior when deploy inside docker. The solution is reverse proxy through the public ip address of your instance (assuming it is directly exposed to the internet with a public IP address). And seems you have already figure out the solution yourself!

If your problem have been resolved and you got no further questions, please close this issue.

**Comment by Morethanevil** [comment] 2024-06-08 02:39
You can set a static IP for Zoraxy. This works too. Then you can use the static IP of Zoraxy and the port inside the container.  You can find a little guide [in the wiki](https://github.com/tobychui/zoraxy/wiki/Zoraxy-in-Docker-with-Portainer-and-Nginx-as-examples)

**Closed as completed** 2024-06-08 02:46 UTC
Labels: help wanted
